FONTS = {
    1: "0,1,2,3,4,5,6,7,8,9",
    2: "۰,۱,۲,۳,۴,۵,۶,۷,۸,۹",
    3: "⓿,➊,➋,➌,➍,➎,➏,➐,➑,➒",
    4: "⓪,①,②,③,④,⑤,⑥,⑦,⑧,⑨",
    5: "０,１,２,３,４,５,６,７,８,９",
    6: "𝟘,𝟙,𝟚,𝟛,𝟜,𝟝,𝟞,𝟟,𝟠,𝟡",
    7: "𝟬,𝟭,𝟮,𝟯,𝟰,𝟱,𝟲,𝟳,𝟴,𝟵",
    8: "𝟎,𝟏,𝟐,𝟑,𝟒,𝟓,𝟔,𝟕,𝟖,𝟗",
    9: "𝟢,𝟣,𝟤,𝟥,𝟦,𝟧,𝟨,𝟩,𝟪,𝟫",
    10: "𝟶,𝟷,𝟸,𝟹,𝟺,𝟻,𝟼,𝟽,𝟾,𝟿",
    11: "₀,₁,₂,₃,₄,₅,₆,₇,₈,₉",
    12: "⁰,¹,²,³,⁴,⁵,⁶,⁷,⁸,⁹",
    13: "⒪,⑴,⑵,⑶,⑷,⑸,⑹,⑺,⑻,⑼",
    14: "0҉,1҉,2҉,3҉,4҉,5҉,6҉,7҉,8҉,9҉",
}

HEARTS = ["❤️", "🩷", "🩵", "🩶", "💙", "💛", "💚", "🧡", "💜", "🖤", "🤍"]

COLORS = ["white", "blue", "red", "yellow", "green", "purple", "orange", "pink", "gold", "skyblue", "gray"]

ACTIONS = [
    "bandari",
    "random",
    "typing",
    "game",
    "photo",
    "audio",
    "video",
    "file",
    "sticker",
    "contact",
    "location",
    "record-video",
    "record-audio",
    "record-round",
]

EDITS ={
    "Bold",
    "Mono",
    "Italic",
    "Underline",
    "Strike",
    "Spoiler",
    "Hashtag",
    "Mention",
}

FOSHS = ["کس ننه","کص ننت","کس خواهر","کس خوار","کس خارت","کس ابجیت","کص لیس","ساک بزن","ساک مجلسی","ننه الکسیس","نن الکسیس","ناموستو گاییدم","ننه زنا","کس خل","کس مخ","کس مغز","کس مغذ","خوارکس","خوار کس","خواهرکس","خواهر کس","حروم زاده","حرومزاده","خار کس","تخم سگ","پدر سگ","پدرسگ","پدر صگ","پدرصگ","ننه سگ","ننه صگ","ننه خراب","مادر سگ","مادر خراب","مادرتو گاییدم","تخم جن","تخم سگ","کس عمت","کس کش","خوار کصده","بی پدرمادر","خارکصده","مادر جنده","کصکش"]

OCRLANGS = {
    "ara": "Arabic",
    "eng": "English",
    "fre": "French",
    "kor": "Korean",
    "ita": "Italian",
    "jpn": "Japanese",
    "chs": "Chinese",
    "ger": "German",
    "spa": "Spanish",
    "swe": "Swedish",
    "tur": "Turkish",
    "bul": "Bulgarian",
    "pol": "Polish",
    "por": "Portugal",
    "rus": "Russian",
    "hrv": "Croatian",
    "hin": "Hindi",
}

TRLANGS = {
    "af": "afrikaans",
    "sq": "albanian",
    "am": "amharic",
    "ar": "arabic",
    "hy": "armenian",
    "as": "assamese",
    "ay": "aymara",
    "az": "azerbaijani",
    "bm": "bambara",
    "eu": "basque",
    "be": "belarusian",
    "bn": "bengali",
    "bho": "bhojpuri",
    "bs": "bosnian",
    "bg": "bulgarian",
    "ca": "catalan",
    "ceb": "cebuano",
    "ny": "chichewa",
    "zh-CN": "chinese (simplified)",
    "zh-TW": "chinese (traditional)",
    "co": "corsican",
    "hr": "croatian",
    "cs": "czech",
    "da": "danish",
    "dv": "dhivehi",
    "doi": "dogri",
    "nl": "dutch",
    "en": "english",
    "eo": "esperanto",
    "et": "estonian",
    "ee": "ewe",
    "tl": "filipino",
    "fi": "finnish",
    "fr": "french",
    "fy": "frisian",
    "gl": "galician",
    "ka": "georgian",
    "de": "german",
    "el": "greek",
    "gn": "guarani",
    "gu": "gujarati",
    "ht": "haitian creole",
    "ha": "hausa",
    "haw": "hawaiian",
    "iw": "hebrew",
    "hi": "hindi",
    "hmn": "hmong",
    "hu": "hungarian",
    "is": "icelandic",
    "ig": "igbo",
    "ilo": "ilocano",
    "id": "indonesian",
    "ga": "irish",
    "it": "italian",
    "ja": "japanese",
    "jw": "javanese",
    "kn": "kannada",
    "kk": "kazakh",
    "km": "khmer",
    "rw": "kinyarwanda",
    "gom": "konkani",
    "ko": "korean",
    "kri": "krio",
    "ku": "kurdish (kurmanji)",
    "ckb": "kurdish (sorani)",
    "ky": "kyrgyz",
    "lo": "lao",
    "la": "latin",
    "lv": "latvian",
    "ln": "lingala",
    "lt": "lithuanian",
    "lg": "luganda",
    "lb": "luxembourgish",
    "mk": "macedonian",
    "mai": "maithili",
    "mg": "malagasy",
    "ms": "malay",
    "ml": "malayalam",
    "mt": "maltese",
    "mi": "maori",
    "mr": "marathi",
    "mni-Mtei": "meiteilon (manipuri)",
    "lus": "mizo",
    "mn": "mongolian",
    "my": "myanmar",
    "ne": "nepali",
    "no": "norwegian",
    "or": "odia (oriya)",
    "om": "oromo",
    "ps": "pashto",
    "fa": "persian",
    "pl": "polish",
    "pt": "portuguese",
    "pa": "punjabi",
    "qu": "quechua",
    "ro": "romanian",
    "ru": "russian",
    "sm": "samoan",
    "sa": "sanskrit",
    "gd": "scots gaelic",
    "nso": "sepedi",
    "sr": "serbian",
    "st": "sesotho",
    "sn": "shona",
    "sd": "sindhi",
    "si": "sinhala",
    "sk": "slovak",
    "sl": "slovenian",
    "so": "somali",
    "es": "spanish",
    "su": "sundanese",
    "sw": "swahili",
    "sv": "swedish",
    "tg": "tajik",
    "ta": "tamil",
    "tt": "tatar",
    "te": "telugu",
    "th": "thai",
    "ti": "tigrinya",
    "ts": "tsonga",
    "tr": "turkish",
    "tk": "turkmen",
    "ak": "twi",
    "uk": "ukrainian",
    "ur": "urdu",
    "ug": "uyghur",
    "uz": "uzbek",
    "vi": "vietnamese",
    "cy": "welsh",
    "xh": "xhosa",
    "yi": "yiddish",
    "yo": "yoruba",
    "zu": "zulu"
}

PVFILTERS = [
    "FILTERPV_MEDIA",
    "FILTERPV_TEXT",
    "FILTERPV_PHOTO",
    "FILTERPV_VIDEO",
    "FILTERPV_GIF",
    "FILTERPV_VOICE",
    "FILTERPV_MUSIC",
    "FILTERPV_STICKER",
    "FILTERPV_FILE",
    "FILTERPV_LINK",
]