STRINGS = {
    "wait": "**⏳ Please Wait ...**",
    "On": "Actived (✔️)",
    "Off": "DeActived (✖️)",
    "LargeSize": "**✘ The File Size Must Be Less Than From:** ( `{}` )",
    "OtherCallback": "🚫 This Is Not Created For You!",
    "OtherInline": "**🚫 This Is Not Created For You!**\n\n**• Don't Use From Bot!**",
    "only": {
        "Pv": "**❉ Please Use This Command Only In The Private Chats!**",
        "Group": "**❉ Please Use This Command Only In The Groups!**",
        "Channel": "**❉ Please Use This Command Only In The Channels!**",
    },
    "reply": "**❉ Please Reply To {}!**",
    "replytext": "**❉ Please Reply To A Text Message!**",
    "user": {
        "all": "**❉ Please Reply To User Or Enter UserID - Username Or Send In Pv!**",
        "reply": "**❉ Please Reply To User!**",
        "replyid": "**❉ Please Reply To User Or Enter UserID - Username!**",
    },
    "chat": {
        "all": "**❉ Please Enter ChatID - ChatUsername Or Send In The Chat!**",
        "id": "**❉ Please Enter ChatID - ChatUsername!**",
    },
    "inline": {
        "On": "( ✔️ )",
        "Off": "( ✖️ )",
        "Yes": "Yes ✅",
        "No": "No ❌",
        "Close": "🚫 Close 🚫",
        "NextPage": "Next ▶️",
        "BackPage": "◀️ Back",
        "Back": "🔙 Back",
        "Delete": "🗑️ Delete 🗑️",
        "Clean": "🗑️ Clean 🗑️",
        "Show": "💡 This Button Is Only For Show!",
    },
    "progress": {
        "Text": "`{}`\n\n`[ {} ]{}%`\n\n**🗃️ Size:** ( `{}` ) - ( `{}` )\n**🚅 Speed:** ( `{}` )\n**⏳ ETA:** ( `{}` )",
        "Down": "📥 Downloading . . .",
        "Up": "📤 Uploading . . .",
    },
}