STRINGS = {
    "wait": "**Please Wait ⏳**",
    "On": "Actived",
    "Off": "DeActived",
    "LargeSize": "**The File Size Must Be Less Than From:** ( `{}` )",
    "OtherCallback": "This Is Not Created For You!",
    "OtherInline": "**This Is Not Created For You!**\n\n**Don't Use From Bot!**",
    "replyMedia": {
        "Main": "**The Replyed Media Is** ( `{}` ) **Please Reply To** ( `{}` )",
        "Not": "**You Have Not Replied Please Reply To** ( `{}` )",
        "NotAll": "**You Have Not Replied Please Reply To A Message!**",
        "Message": "Message",
        "Text": "Text",
        "Photo": "Photo",
        "Video": "Video",
        "VideoNote": "Video Note",
        "Gif": "Gif",
        "Voice": "Voice",
        "Music": "Music",
        "Sticker": "Sticker",
        "ASticker": "Animated Sticker",
        "File": "File",
        "Empty": "Empty",
    },
    "getid": {
        "IU": "**The Entered UserID Is Not Valid!**",
        "U": "**Please Reply To User!**",
        "UU": "**Please Reply To User Or Enter Username!**",
        "UUP": "**Please Reply To User Or Enter UserID Or Send In Pv!**",
        "UC": "**Please Enter Chat Username Or Send In Chat!**",
        "UCH": "**Please Enter Channel Username Or Send In Channel!**",
    },
    "inline": {
        "On": "❲ ✅ ❳",
        "Off": "❲ ❌ ❳",
        "Close": "🚫 Close 🚫",
        "Next": "Next ▶️",
        "Back": "◀️ Back",
        "Show": "This Button Is Only For Show!",
    },
    "progress": {
        "Text": "`{}`\n\n`[ {} ]{}%`\n\n**Size:** ( `{}` ) - ( `{}` )\n**Speed:** ( `{}` )\n**ETA:** ( `{}` )",
        "Down": "Downloading . . .",
        "Up": "Uploading . . .",
    },
}