STRINGS = {
    "wait": "**⏳ Please Wait ...**",
    "On": "Actived(✔️)",
    "Off": "DeActived(✖️)",
    "LargeSize": "**✘ The File Size Must Be Less Than From:** ( `{}` )",
    "OtherCallback": "🚫 This Is Not Created For You!",
    "OtherInline": "**🚫 This Is Not Created For You!**\n\n**• Don't Use From Bot!**",
    "only": {
        "Pv": "**❉ Please Use This Command Only In The Private Chats!",
        "Group": "**❉ Please Use This Command Only In The Groups!",
        "Channel": "**❉ Please Use This Command Only In The Channels!",
    },
    "reply": "**❉ Please Reply To** {}",
    "replytext": "**❉ Please Reply To A Text Message!**",
    "getuserID": "**❉ Please Reply To User Or Enter UserID Or Send In Pv!**", 
    "getchatID": "**❉ Please Enter ChatID Or Send In The Chat!**", 
    "getid": {
        "IU": "**❉ The Entered UserID Is Not Valid!**",
        "U": "**❉ Reply To Message From User!**",
        "UU": "**❉ Please Reply To User Or Enter Username!**",
        "UUP": "**❉ Please Reply To User Or Enter UserID Or Send In Pv!**",
        "UC": "**❉ Please Enter Chat Username Or Send In Chat!**",
        "UCH": "**❉ Please Enter Channel Username Or Send In Channel!**",
    },
    "inline": {
        "On": "( ✔️ )",
        "Off": "( ✖️ )",
        "Yes": "Yes ✅",
        "No": "No ❌",
        "Close": "🚫 Close 🚫",
        "NextPage": "Next ▶️",
        "BackPage": "◀️ Back",
        "Back": "🔙 Back",
        "Delete": "🗑️ Delete 🗑️",
        "Show": "💡 This Button Is Only For Show!",
    },
    "progress": {
        "Text": "`{}`\n\n`[ {} ]{}%`\n\n**🗃️ Size:** ( `{}` ) - ( `{}` )\n**🚅 Speed:** ( `{}` )\n**⏳ ETA:** ( `{}` )",
        "Down": "📥 Downloading . . .",
        "Up": "📤 Uploading . . .",
    },
}